'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="NFC")>  _
Partial Public Class NFCDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("NFCConnectionString1").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.QryLoginNFC")>  _
	Public Function QryLoginNFC(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Usuario", DbType:="VarChar(10)")> ByVal usuario As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Clave", DbType:="VarChar(10)")> ByVal clave As String) As ISingleResult(Of QryLoginNFCResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), usuario, clave)
		Return CType(result.ReturnValue,ISingleResult(Of QryLoginNFCResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.QryObtenerMateriasxDocente")>  _
	Public Function QryObtenerMateriasxDocente(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdDocente", DbType:="Int")> ByVal idDocente As System.Nullable(Of Integer)) As ISingleResult(Of QryObtenerMateriasxDocenteResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idDocente)
		Return CType(result.ReturnValue,ISingleResult(Of QryObtenerMateriasxDocenteResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.spingresartest")>  _
	Public Function spingresartest(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal idmateria As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal titulo As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(300)")> ByVal descripcion As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(MAX)")> ByVal preguntas As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(MAX)")> ByVal respuestas As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(MAX)")> ByVal correctas As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByRef idtest As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idmateria, titulo, descripcion, preguntas, respuestas, correctas, idtest)
		idtest = CType(result.GetParameterValue(6),System.Nullable(Of Integer))
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

Partial Public Class QryLoginNFCResult
	
	Private _id As Integer
	
	Private _nombre As String
	
	Private _identificacion As String
	
	Private _tipo As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id", DbType:="Int NOT NULL")>  _
	Public Property id() As Integer
		Get
			Return Me._id
		End Get
		Set
			If ((Me._id = value)  _
						= false) Then
				Me._id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre", DbType:="NVarChar(101)")>  _
	Public Property nombre() As String
		Get
			Return Me._nombre
		End Get
		Set
			If (String.Equals(Me._nombre, value) = false) Then
				Me._nombre = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_identificacion", DbType:="NVarChar(10)")>  _
	Public Property identificacion() As String
		Get
			Return Me._identificacion
		End Get
		Set
			If (String.Equals(Me._identificacion, value) = false) Then
				Me._identificacion = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tipo", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property tipo() As String
		Get
			Return Me._tipo
		End Get
		Set
			If (String.Equals(Me._tipo, value) = false) Then
				Me._tipo = value
			End If
		End Set
	End Property
End Class

Partial Public Class QryObtenerMateriasxDocenteResult
	
	Private _IdMateria As Integer
	
	Private _Nombre As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdMateria", DbType:="Int NOT NULL")>  _
	Public Property IdMateria() As Integer
		Get
			Return Me._IdMateria
		End Get
		Set
			If ((Me._IdMateria = value)  _
						= false) Then
				Me._IdMateria = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Nombre", DbType:="VarChar(50)")>  _
	Public Property Nombre() As String
		Get
			Return Me._Nombre
		End Get
		Set
			If (String.Equals(Me._Nombre, value) = false) Then
				Me._Nombre = value
			End If
		End Set
	End Property
End Class
