'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Test
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''cbMaterias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMaterias As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txTitulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txDescripcion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txPregunta1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP1R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP1R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP1R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP1R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP1R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP1R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP1R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP1R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP1R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP1R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP1R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP1R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP1R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP1R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP1R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP1R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP1R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP1R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP1R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP1R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP2R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP2R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP2R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP2R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP2R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP2R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP2R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP2R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP2R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP2R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP2R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP2R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP2R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP2R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP2R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP2R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP2R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP2R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP2R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP2R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP3R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP3R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP3R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP3R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP3R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP3R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP3R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP3R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP3R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP3R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP3R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP3R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP3R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP3R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP3R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP3R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP3R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP3R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP3R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP3R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP4R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP4R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP4R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP4R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP4R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP4R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP4R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP4R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP4R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP4R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP4R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP4R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP4R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP4R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP4R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP4R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP4R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP4R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP4R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP4R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP5R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP5R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP5R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP5R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP5R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP5R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP5R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP5R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP5R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP5R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP5R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP5R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP5R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP5R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP5R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP5R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP5R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP5R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP5R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP5R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP6R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP6R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP6R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP6R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP6R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP6R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP6R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP6R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP6R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP6R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP6R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP6R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP6R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP6R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP6R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP6R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP6R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP6R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP6R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP6R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP7R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP7R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP7R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP7R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP7R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP7R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP7R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP7R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP7R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP7R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP7R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP7R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP7R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP7R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP7R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP7R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP7R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP7R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP7R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP7R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP8R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP8R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP8R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP8R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP8R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP8R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP8R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP8R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP8R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP8R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP8R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP8R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP8R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP8R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP8R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP8R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP8R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP8R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP8R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP8R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP9R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP9R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP9R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP9R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP9R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP9R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP9R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP9R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP9R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP9R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP9R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP9R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP9R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP9R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP9R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP9R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP9R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP9R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP9R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP9R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txPregunta10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPregunta10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txP10R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP10R1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP10R1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP10R1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP10R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP10R2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP10R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP10R2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP10R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP10R3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP10R3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP10R3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP10R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP10R4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP10R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP10R4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txP10R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txP10R5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbP10R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbP10R5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''btnRegisterTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegisterTest As Global.System.Web.UI.WebControls.Button
End Class
